/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesTowersRouteImport } from './routes/games.towers'
import { Route as GamesSlotsRouteImport } from './routes/games.slots'
import { Route as GamesRouletteRouteImport } from './routes/games.roulette'
import { Route as GamesMinesRouteImport } from './routes/games.mines'
import { Route as GamesKenoRouteImport } from './routes/games.keno'
import { Route as GamesDiceRouteImport } from './routes/games.dice'
import { Route as GamesCrashRouteImport } from './routes/games.crash'
import { Route as GamesCoinflipRouteImport } from './routes/games.coinflip'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTowersRoute = GamesTowersRouteImport.update({
  id: '/games/towers',
  path: '/games/towers',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlotsRoute = GamesSlotsRouteImport.update({
  id: '/games/slots',
  path: '/games/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRouletteRoute = GamesRouletteRouteImport.update({
  id: '/games/roulette',
  path: '/games/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMinesRoute = GamesMinesRouteImport.update({
  id: '/games/mines',
  path: '/games/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesKenoRoute = GamesKenoRouteImport.update({
  id: '/games/keno',
  path: '/games/keno',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDiceRoute = GamesDiceRouteImport.update({
  id: '/games/dice',
  path: '/games/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCrashRoute = GamesCrashRouteImport.update({
  id: '/games/crash',
  path: '/games/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCoinflipRoute = GamesCoinflipRouteImport.update({
  id: '/games/coinflip',
  path: '/games/coinflip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/tournaments': typeof TournamentsRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/games/coinflip': typeof GamesCoinflipRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/dice': typeof GamesDiceRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/towers': typeof GamesTowersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/tournaments': typeof TournamentsRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/games/coinflip': typeof GamesCoinflipRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/dice': typeof GamesDiceRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/towers': typeof GamesTowersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/tournaments': typeof TournamentsRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/games/coinflip': typeof GamesCoinflipRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/dice': typeof GamesDiceRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/towers': typeof GamesTowersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/missions'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/support'
    | '/tournaments'
    | '/vip'
    | '/wallet'
    | '/games/coinflip'
    | '/games/crash'
    | '/games/dice'
    | '/games/keno'
    | '/games/mines'
    | '/games/roulette'
    | '/games/slots'
    | '/games/towers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/missions'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/support'
    | '/tournaments'
    | '/vip'
    | '/wallet'
    | '/games/coinflip'
    | '/games/crash'
    | '/games/dice'
    | '/games/keno'
    | '/games/mines'
    | '/games/roulette'
    | '/games/slots'
    | '/games/towers'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/missions'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/support'
    | '/tournaments'
    | '/vip'
    | '/wallet'
    | '/games/coinflip'
    | '/games/crash'
    | '/games/dice'
    | '/games/keno'
    | '/games/mines'
    | '/games/roulette'
    | '/games/slots'
    | '/games/towers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RewardsRoute: typeof RewardsRoute
  SupportRoute: typeof SupportRoute
  TournamentsRoute: typeof TournamentsRoute
  VipRoute: typeof VipRoute
  WalletRoute: typeof WalletRoute
  GamesCoinflipRoute: typeof GamesCoinflipRoute
  GamesCrashRoute: typeof GamesCrashRoute
  GamesDiceRoute: typeof GamesDiceRoute
  GamesKenoRoute: typeof GamesKenoRoute
  GamesMinesRoute: typeof GamesMinesRoute
  GamesRouletteRoute: typeof GamesRouletteRoute
  GamesSlotsRoute: typeof GamesSlotsRoute
  GamesTowersRoute: typeof GamesTowersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/towers': {
      id: '/games/towers'
      path: '/games/towers'
      fullPath: '/games/towers'
      preLoaderRoute: typeof GamesTowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/slots': {
      id: '/games/slots'
      path: '/games/slots'
      fullPath: '/games/slots'
      preLoaderRoute: typeof GamesSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/roulette': {
      id: '/games/roulette'
      path: '/games/roulette'
      fullPath: '/games/roulette'
      preLoaderRoute: typeof GamesRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/mines': {
      id: '/games/mines'
      path: '/games/mines'
      fullPath: '/games/mines'
      preLoaderRoute: typeof GamesMinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/keno': {
      id: '/games/keno'
      path: '/games/keno'
      fullPath: '/games/keno'
      preLoaderRoute: typeof GamesKenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/dice': {
      id: '/games/dice'
      path: '/games/dice'
      fullPath: '/games/dice'
      preLoaderRoute: typeof GamesDiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/crash': {
      id: '/games/crash'
      path: '/games/crash'
      fullPath: '/games/crash'
      preLoaderRoute: typeof GamesCrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/coinflip': {
      id: '/games/coinflip'
      path: '/games/coinflip'
      fullPath: '/games/coinflip'
      preLoaderRoute: typeof GamesCoinflipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RewardsRoute: RewardsRoute,
  SupportRoute: SupportRoute,
  TournamentsRoute: TournamentsRoute,
  VipRoute: VipRoute,
  WalletRoute: WalletRoute,
  GamesCoinflipRoute: GamesCoinflipRoute,
  GamesCrashRoute: GamesCrashRoute,
  GamesDiceRoute: GamesDiceRoute,
  GamesKenoRoute: GamesKenoRoute,
  GamesMinesRoute: GamesMinesRoute,
  GamesRouletteRoute: GamesRouletteRoute,
  GamesSlotsRoute: GamesSlotsRoute,
  GamesTowersRoute: GamesTowersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
